project: default
source:
  repoURL: 'https://github.com/kaytalkcity/eks-example.git'
  path: prometheus
destination:
  server: 'https://kubernetes.default.svc'
syncPolicy:
  automated:
    prune: true
    selfHeal: true
