apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-crd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kube-prometheus-stack/crds
    repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true