apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 15.11.0
    chart: prometheus
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccounts.server.annotations."eks\.amazonaws\.com/role-arn"
          value: 'arn:aws:iam::ACCOUNT_ID:role/amp-one-iamproxy-ingest-role'
        - name: 'server.remoteWrite[0].url'
          value: >-
            https://aps-workspaces.us-east-1.amazonaws.com/workspaces/PROMETEHEUS_WORKSPACE_ID/api/v1/remote_write
        - name: 'server.remoteWrite[0].sigv4.region'
          value: us-east-1
      values: |-
        serviceAccounts:
          ## Disable alert manager roles
          ##
          server:
                name: "amp-one-iamproxy-ingest-service-account"
          alertmanager:
            create: false

          ## Disable pushgateway
          ##
          pushgateway:
            create: false

        server:
          remoteWrite:
            -
              queue_config:
                max_samples_per_send: 1000
                max_shards: 200
                capacity: 2500

          ## Use a statefulset instead of a deployment for resiliency
          ##
          statefulSet:
            enabled: true

          ## Store blocks locally for short time period only
          ##
          retention: 1h

        ## Disable alert manager
        ##
        alertmanager:
          enabled: false

        ## Disable pushgateway
        ##
        pushgateway:
          enabled: false
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
