apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: rate
  namespace: http-proxy
spec:
  virtualhost:
    fqdn: rate.sanniolo.myinstance.com
    rateLimitPolicy:
      local:
        requests: 2
        unit: minute
  routes:
    - conditions:
      - prefix: /
      services:
        - name: nginx
          port: 80