apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-app-sync-status
  namespace: argocd
  labels:
    release: prometheus
spec:
  groups:
    - name: EmbeddedExporter
      rules:
        - alert: CorednsPanicCount
          expr: 'increase(coredns_panics_total[1m]) > 0'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "'{{ $labels.name }}' Application has sync status as '{{ $labels.sync_status }}'"
          annotations:
            summary: "CoreDNS Panic Count (instance {{ $labels.instance }})"
            description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
