apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: instance_path_requests
  namespace: argocd
  labels:
    release: prometheus
spec:
  groups:
    - name: AlertManager
      rules:
        # Aggregating up requests per second that has a path label:
        - record: instance_path_requests
          expr: count(ALERTS{alertstate="firing"})
