apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-memory-MemFree-percent
  namespace: argocd
  labels:
    release: prometheus
spec:
  groups:
    - name: custom_rules
      rules:
        - record: node_memory_MemFree_percent
          expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)
  
        - record: node_filesystem_free_percent
          expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}
