apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: instance_path_requests_failure
  namespace: argocd
  labels:
    release: prometheus
spec:
  groups:
    - name: AlertManager
      rules:
        # Calculating a request failure ratio and aggregating up to the job-level failure ratio:
        - record: instance_path:request_failures:rate5m
          expr: rate(request_failures_total{job="myjob"}[5m])
        
        - record: instance_path:request_failures_per_requests:ratio_rate5m
          expr: |2
              instance_path:request_failures:rate5m{job="myjob"}
            /
              instance_path:requests:rate5m{job="myjob"}
        # Aggregate up numerator and denominator, then divide to get path-level ratio.
        - record: path:request_failures_per_requests:ratio_rate5m
          expr: |2
              sum without (instance)(instance_path:request_failures:rate5m{job="myjob"})
            /
              sum without (instance)(instance_path:requests:rate5m{job="myjob"})
        # No labels left from instrumentation or distinguishing instances,
        # so we use 'job' as the level.
        - record: job:request_failures_per_requests:ratio_rate5m
          expr: |2
              sum without (instance, path)(instance_path:request_failures:rate5m{job="myjob"})
            /
              sum without (instance, path)(instance_path:requests:rate5m{job="myjob"})
