apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.32.10
    chart: grafana
    helm:
      valueFiles:
        - values.yaml
      values: |-
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus.svc.cluster.local
              access: proxy
              isDefault: true
      parameters:
        - name: persistence.size
          value: 15Gi
        - name: service.type
          value: LoadBalancer
        - name: persistence.storageClassName
          value: gp2
        - name: persistence.enabled
          value: 'true'
        - name: adminPassword
          value: EKS!sAWSome
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true