apiVersion: v1
kind: Namespace
metadata:
  name: demo-app2
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-self
  namespace: demo-app2
spec:
  secretName: test-tls
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  dnsNames:
  - '*.sanniolo.myinstance.com'
  - sanniolo.myinstance.com
  #- httpbin.sanniolo.myinstance.com